### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by zer0mania** [Spliterash/HttpCommandExecutor#1]
![image](https://user-images.githubusercontent.com/48740591/227813795-76d8c263-4c5f-4078-b51b-a132814a1129.png)

Error execute command(CommandException): Unhandled exception executing 'weather clear' in org.bukkit.craftbukkit.v1_19_R3.command.VanillaCommandWrapper(weather)

1.19.4 paper mc

**Comment by Spliterash** [comment]
Fixed, you need add header `mode` with `console` value, but you can't get output. 
This happens, because vanilla command's not like custom CommandSender, so as a solution i just run the command as console

You can download fix from spigot
